#' Exam Notes 2: Conditional Flow, Loops, and Nested Loops
#'
#' Provides a cheat sheet with notes on conditional flow, loops, and nested loops.
#'
#' @return A string containing formatted exam notes for quick reference.
#' @examples
#' exam_notes2()
#' @export
exam_notes2 <- function() {
  paste(
    "### Exam Notes 2: Quick R Reference",
    "",
    "### 1. Conditional Flow",
    "  - **`if(cond)`**: Runs code if `cond` is TRUE. Use `else if` and `else` for alternatives.",
    "    - Example:",
    "      ```R",
    "      x <- 5",
    "      if(x > 10) {",
    "        print('Greater than 10')",
    "      } else if(x == 5) {",
    "        print('Equal to 5')",
    "      } else {",
    "        print('Less than 5')",
    "      }",
    "      ```",
    "",
    "  - **`ifelse(test, yes, no)`**: Vectorized if-else for quick checks.",
    "    - Example: `ifelse(1:5 %% 2 == 0, 'even', 'odd')`",
    "",
    "  - Combine conditions:",
    "    - **`&&`**: Logical AND (both conditions must be TRUE).",
    "    - **`||`**: Logical OR (at least one condition must be TRUE).",
    "    - **`!`**: Logical NOT (negates TRUE to FALSE).",
    "    - Example: `if(x > 0 && y < 0)`",
    "",
    "---",
    "",
    "### 2. Loops",
    "  - **`for(i in 1:10)`**: Iterates over a range or vector.",
    "    - Example:",
    "      ```R",
    "      for(i in 1:5) {",
    "        print(i)",
    "      }",
    "      ```",
    "",
    "  - **`while(cond)`**: Repeats while `cond` is TRUE.",
    "    - Example:",
    "      ```R",
    "      wallet <- 10",
    "      while(wallet > 0) {",
    "        wallet <- wallet - 2",
    "        print(wallet)",
    "      }",
    "      ```",
    "",
    "  - **`break`**: Stops a loop immediately.",
    "    - Example:",
    "      ```R",
    "      for(i in 1:10) {",
    "        if(i == 5) break",
    "        print(i)",
    "      }",
    "      ```",
    "",
    "  - **`next`**: Skips to the next iteration.",
    "    - Example:",
    "      ```R",
    "      for(i in 1:10) {",
    "        if(i %% 2 == 0) next",
    "        print(i)",
    "      }",
    "      ```",
    "",
    "---",
    "",
    "### 3. Nested Loops",
    "  - Use nested loops for multi-layered tasks:",
    "    ```R",
    "    combi <- 189",
    "    solved <- FALSE",
    "    for(i in 1:9) {",
    "      for(j in 1:9) {",
    "        for(k in 1:9) {",
    "          if(!solved) {",
    "            solved <- paste0(i, j, k) == combi",
    "          }",
    "        }",
    "      }",
    "    }",
    "    ```",
    sep = "\n"
  )
}
