exam_notes1 <- function() {
  cat(
    "### Basic R Functions\n",
    "- **rep(x, times, each, length.out)**: Repeat values in various ways.\n",
    "  - `rep(5, times=3)` -> 5, 5, 5\n",
    "  - `rep(1:3, each=2)` -> 1, 1, 2, 2, 3, 3\n",
    "  - `rep(1:3, length.out=7)` -> 1, 2, 3, 1, 2, 3, 1\n",
    "- **seq(from, to, by)**: Generate sequences.\n",
    "  - `seq(1, 10, 2)` -> 1, 3, 5, 7, 9\n",
    "  - `seq(5, -5, -2)` -> 5, 3, 1, -1, -3, -5\n",
    "- **head(x, n=6)**: View the first n rows of data. Example: `head(mtcars, 3)` -> First 3 rows of `mtcars`.\n",
    "- **write.csv(df, file)**: Save a data frame to a .csv file. Example: `write.csv(mtcars, 'cars.csv', row.names=FALSE)`\n",
    "- **sample(x, size, replace=F, prob=NULL)**: Random sampling.\n",
    "  - `sample(1:10, 5)` -> Random 5 numbers from 1 to 10 without replacement.\n",
    "  - `sample(c('A','B','C'), size=4, replace=TRUE, prob=c(0.5,0.3,0.2))`: \"A\" has a 50% chance, \"B\" 30%, \"C\" 20%.\n",
    "- **paste(..., sep, collapse)**: Combine strings.\n",
    "  - `paste('Hello', 'World', sep=' ')` -> 'Hello World'\n",
    "  - `paste(c('a', 'b'), collapse=',')` -> 'a,b'\n",
    "\n---\n\n",
    "### Time Formatting\n",
    "- **Format Codes for Dates/Times**:\n",
    "  - `%Y`: Year (4 digits). `%y`: Year (last 2 digits).\n",
    "  - `%m`: Month. `%d`: Day of the month.\n",
    "  - `%H`: Hour (24-hour). `%I`: Hour (12-hour).\n",
    "  - `%M`: Minute. `%S`: Second. `%p`: AM/PM.\n",
    "  - Example: `format(Sys.Date(), '%Y-%m-%d')` -> '2025-01-24'.\n",
    "\n---\n\n",
    "### Visualization\n",
    "- **plot(x, y)**: Quick scatterplot.\n",
    "  - Example: `plot(mtcars$mpg, mtcars$hp)`\n",
    "- **ggplot2**: Flexible visualizations.\n",
    "  - **Basic**: `ggplot(df, aes(x, y)) + geom_point()`\n",
    "  - **Regression**: Add a line: `geom_smooth(method='lm', se=FALSE)`\n",
    "  - **Customizations**:\n",
    "    - Use `aes(color=var)` or `aes(shape=var)` for grouping.\n",
    "    - Clean layout: Add `theme_bw()` or `theme_minimal()`.\n",
    "    - Example with jitter:\n",
    "      ggplot(df, aes(x, y)) +\n",
    "        geom_jitter(width=0.2, height=0.2) +\n",
    "        geom_smooth(method='lm') +\n",
    "        theme_bw()\n",
    "- **par(mfrow=c(r, c))**: Multi-panel plots.\n",
    "  - Example: `par(mfrow=c(2, 2)); plot(x, y); hist(z); boxplot(w); plot(q)`\n"
  )
}
