exam_notes2 <- function() {
  cat(
    "### Exam Notes 2: Quick R Reference\n\n",
    "### 1. Conditional Flow\n",
    "  - **`if(cond)`**: Runs code if `cond` is TRUE. Use `else if` and `else` for alternatives.\n",
    "    - Example:\n",
    "      ```R\n",
    "      x <- 5\n",
    "      if(x > 10) {\n",
    "        print('Greater than 10')\n",
    "      } else if(x == 5) {\n",
    "        print('Equal to 5')\n",
    "      } else {\n",
    "        print('Less than 5')\n",
    "      }\n",
    "      ```\n\n",
    "  - **`ifelse(test, yes, no)`**: Vectorized if-else for quick checks.\n",
    "    - Example: `ifelse(1:5 %% 2 == 0, 'even', 'odd')`\n\n",
    "  - Combine conditions:\n",
    "    - **`&&`**: Logical AND (both conditions must be TRUE).\n",
    "    - **`||`**: Logical OR (at least one condition must be TRUE).\n",
    "    - **`!`**: Logical NOT (negates TRUE to FALSE).\n",
    "    - Example: `if(x > 0 && y < 0)`\n\n",
    "---\n\n",
    "### 2. Loops\n",
    "  - **`for(i in 1:10)`**: Iterates over a range or vector.\n",
    "    - Example:\n",
    "      ```R\n",
    "      for(i in 1:5) {\n",
    "        print(i)\n",
    "      }\n",
    "      ```\n\n",
    "  - **`while(cond)`**: Repeats while `cond` is TRUE.\n",
    "    - Example:\n",
    "      ```R\n",
    "      wallet <- 10\n",
    "      while(wallet > 0) {\n",
    "        wallet <- wallet - 2\n",
    "        print(wallet)\n",
    "      }\n",
    "      ```\n\n",
    "  - **`break`**: Stops a loop immediately.\n",
    "    - Example:\n",
    "      ```R\n",
    "      for(i in 1:10) {\n",
    "        if(i == 5) break\n",
    "        print(i)\n",
    "      }\n",
    "      ```\n\n",
    "  - **`next`**: Skips to the next iteration.\n",
    "    - Example:\n",
    "      ```R\n",
    "      for(i in 1:10) {\n",
    "        if(i %% 2 == 0) next\n",
    "        print(i)\n",
    "      }\n",
    "      ```\n\n",
    "---\n\n",
    "### 3. Nested Loops\n",
    "  - Use nested loops for multi-layered tasks:\n",
    "    ```R\n",
    "    combi <- 189\n",
    "    solved <- FALSE\n",
    "    for(i in 1:9) {\n",
    "      for(j in 1:9) {\n",
    "        for(k in 1:9) {\n",
    "          if(!solved) {\n",
    "            solved <- paste0(i, j, k) == combi\n",
    "          }\n",
    "        }\n",
    "      }\n",
    "    }\n",
    "    ```\n\n"
  )
}
